[package]
name = "aoc_24"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"
ndarray = "0.16.1"
nom = "7.1.3"
rstest = "0.23.0"
strum_macros = "0.26.4"
vek = "0.17.1"
